blank_issues_enabled: true
contact_links:
- name: Bibliographic Source
  url:  https://github.com/dwhieb/dissertation/issues/new?projects=dwhieb/dissertation/1&labels=bibliography
  about: A bibliographic source
