name: tests

on:
  pull_request:
  push:
    branches:
      main

jobs:
  run-tests:
    name:    run tests
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v1

      - name: install Node.js
        uses: actions/setup-node@master
        with:
          node-version: 15.x

      - name: install dependencies
        run:  npm ci

      - name: run tests
        run:  npm test
